-------------------------------- MODULE Gate --------------------------------
(***************************************************************************)
(* Harness-owned postcondition guards for the v2 problem set.              *)
(*                                                                          *)
(* This module is CENTRALLY OWNED. It is the shared interface between       *)
(* §5.3 (vacuity probes, tla-kl5.6) and §5.4 (refinement checking,          *)
(* tla-kl5.7), which are built in parallel — so it lives here rather than   *)
(* being written twice.                                                     *)
(*                                                                          *)
(* IT MUST STAY A SEPARATE MODULE. Putting these operators in the spec      *)
(* under test yields "Circular dependency among .tla files"; and when the   *)
(* root module is the one holding the operator, `-postCondition Module!Op`  *)
(* fails outright with "Parsing or semantic analysis failed". Do not        *)
(* inline it later.                                                         *)
(*                                                                          *)
(* Every operator below was verified on TLC 2026.03.04.183147 and           *)
(* re-verified unchanged on tla2tools v1.8.0 (TLC 2026.07.31.184830).       *)
(***************************************************************************)
EXTENDS Naturals, TLC

(***************************************************************************)
(* THE STATE SPACE IS NON-EMPTY.                                            *)
(*                                                                          *)
(* An unsatisfiable Init yields "No error has been found", "0 states        *)
(* generated", and rc=0. Deadlock checking does NOT catch it. Fires         *)
(* correctly even at 0 initial states.                                      *)
(*                                                                          *)
(* The threshold is PER-PROBLEM, not a constant — 4 is a placeholder. Use a *)
(* threshold (>=), never exact equality: TLAiBench shipped an exact         *)
(* state-count fingerprint and relaxed it in the field within hours         *)
(* (commit ba95443), which is also third-party corroboration of §3.5.       *)
(***************************************************************************)
NonVacuous == TLCGet("distinct") >= 4

(***************************************************************************)
(* THE CHECK WAS ACTUALLY CONFIGURED.                                       *)
(*                                                                          *)
(* A second vacuity vector, distinct from NonVacuous above and NOT caught   *)
(* by it. A .cfg keyword with no operand is not an error: given             *)
(* `SPECIFICATION Spec` plus a bare `INVARIANT` line, TLC reports "Model    *)
(* checking completed. No error has been found." at rc=0 having checked no  *)
(* invariant at all. NonVacuous passes it, because the state space is       *)
(* perfectly healthy — it is not the state space that is empty, it is the   *)
(* OBLIGATION.                                                              *)
(*                                                                          *)
(* Verified: rc=10 on a bare `INVARIANT` line, rc=0 on a real one.          *)
(***************************************************************************)
InvariantConfigured == TLCGet("spec").invariants # {}

(***************************************************************************)
(* THE REFINEMENT CHECK WAS ACTUALLY CONFIGURED.                            *)
(*                                                                          *)
(* The same family, one field over: catches a .cfg that never declared the  *)
(* refinement PROPERTY, which otherwise exits 0 silently.                   *)
(*                                                                          *)
(* Adapted from tlaplus/TLAiBench, gold/DieHardGold.tla:137-141             *)
(* (MIT, (c) 2025 TLA+ Foundation).                                         *)
(*                                                                          *)
(* Verified: rc=10 with no PROPERTY line, rc=0 with one.                    *)
(*                                                                          *)
(* RUN IT ALONGSIDE §5.4's frozen-mapping INVARIANT Probe, NEVER INSTEAD    *)
(* OF IT. They catch disjoint failures:                                     *)
(*   no PROPERTY in the cfg      -> this guard fires, the probe is silent   *)
(*   PROPERTY present but frozen -> this guard is silent, the probe fires   *)
(* TLAiBench has only this half, which is why a constant mapping scores a   *)
(* pass on the only public benchmark that grades TLA+ refinement.           *)
(***************************************************************************)
RefinementConfigured ==
    /\ TLCGet("spec").impliedinits   # {}
    /\ TLCGet("spec").impliedactions # {}

(***************************************************************************)
(* ActionPropertyConfigured -- the same guard for §5.2's step obligations.  *)
(*                                                                          *)
(* RefinementConfigured does NOT cover them, and the difference is measured *)
(* rather than reasoned. A refinement PROPERTY populates impliedinits and   *)
(* impliedactions both, because Abstract!Spec carries an Init. A bare boxed *)
(* action carries no Init, so on v1.8.0 a well-formed                       *)
(* PROPERTY GRADE_OBLIGATION over [][Step(Observe, Observe')]_Observe gives *)
(* impliedactions |-> {[name |-> "GRADE_OBLIGATION", ...]} with             *)
(* invariants, impliedinits and temporals all empty. So both                *)
(* RefinementConfigured and InvariantConfigured return rc=10 on a perfectly *)
(* good grading run.                                                        *)
(*                                                                          *)
(* The vector this closes is the one InvariantConfigured exists for, one    *)
(* keyword over: a PROPERTY line with no operand is not an error. TLC exits *)
(* 0 having checked nothing at all.                                         *)
(***************************************************************************)
ActionPropertyConfigured ==
    TLCGet("spec").impliedactions # {}

=============================================================================
